
name: lantern-delta
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Use dry-run (no network/AI)'
        required: false
        default: 'true'
  schedule:
    - cron: '17 2 * * *'
permissions:
  contents: write
jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: python -m pip install --upgrade pip pyyaml
      - name: Probe OPENAI key presence (masked)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -n "${OPENAI_API_KEY:-}" ]; then echo "OPENAI_API_KEY is present."; else echo "OPENAI_API_KEY is MISSING."; fi
      - name: Diagnostics
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/diagnostics.py
      - name: Run review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/run_review.py --spec reviews/iron_esa.yaml --root . $( [ "${{ github.event.inputs.dry_run }}" = "true" ] && echo "--dry-run" ) --limit 50
      - name: Commit data updates
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add data logs || true
          git commit -m "update data ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || echo "no changes"
          git push || true
      - name: Upload artifact (site)
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
  deploy:
    needs: build-and-update
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
